name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: WorkerVless2sub
    steps:
      - name: Sync Fork with Upstream
        uses: tgymnich/fork-sync@v2.0
        with:
          base: master # Base branch of your fork
          head: master # Branch of the upstream repo to sync from
